import Head from "next/head";
import Image from "next/image";
import styles from "./Home.module.css";

import heroCar from "../../public/hero.jpg";
import car1 from "../../public/car1.jpg";
import car2 from "../../public/car2.jpg";
import car3 from "../../public/car3.jpg";

const HomeContainer = () => (
  <main className={styles.main}>
    <Head>
      <title>NextJS | Optimised Images</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <h1 className={styles.heading}>Gatsby Optimised Images</h1>

    <section className={styles.heroImage}>
      <Image
        src={heroCar}
        alt="Hero Car"
        placeholder="blur"
        layout="fixed"
        width={1200}
        height={800}
        quality={80}
        priority
      />
    </section>

    <section className={styles.otherImages}>
      {[car1, car2, car3].map((car, idx) => (
        <Image
          key={idx}
          src={car}
          alt={`Car ${idx + 1}`}
          placeholder="blur"
          layout="fixed"
          width={450}
          height={300}
          quality={50}
        />
      ))}
    </section>
  </main>
);

export default HomeContainer;
